#                                     ArmorStandEditor-Configuration

#General Configuration
ConfigVersion: "1.0"

#Languages - ENGLISH, DEUTSCH
Language: "ENGLISH"

#The item that you have to interact with in order to edit an ArmorStand
#Singleuse = Use the Item like a token, after usage one amount will be removed
Item:
  Type: "FLINT"
  RequireDisplayname: true
  Displayname: "&bArmorStand&8-&bEditor"
  RequireLore: true
  Lore: "&7A tool to edit an ArmorStand"
  SingleUse: false

#Usage
RequirePermission: true
PermissionUsage: "ArmorStandEditor.EditArmorStands"

#GetItem
PermissionGetItem: "ArmorStandEditor.GetItem"

#Shows the current Value of the position/alignment in the Actionbar
ActionbarValues: true
